version: "3"
services:
  web:
    depends_on:
      - db
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - /app/node_modules
      - ./web:/app/
    environment:
      - MYSQLUSER=root
      - MYSQLPORT=3306
      - MYSQLDATABASE=mysql
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/tmp
    ports:
      - "3306:3306"